# ??? ?? ??
debug: false

# Actuator? ?? ????? ??
management:
  endpoints:
    web:
      exposure:
        include: "*"

# ?? ?? ??
logging:
  level:
    board: debug  # board ??? ??
    org.springframework.web.servlet: debug  # Spring ?????? servlet ??? ?? => http ?? ?? ?? ??? ???
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # hibernate ?? ? ??? ?? ?? ?? ??

spring:
  # datasource ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: woong
    password: woong
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa ?? ??
  jpa:
    defer-datasource-initialization: true   # ???? ??? ??? (resources ?? ?? data.sql ?? ???? ??)
    hibernate:
      ddl-auto: create  # ??? ???? ???? ??? create ??
    show-sql: true  # jpa?? ???? sql ???? ??
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100   # entity ?? ???? N + 1 ?? ??? ???? ?? ?? ???? in?? ????? ? ?? ???? ? ?? in ?? ??? ???? ?? ??

  h2:
    console:
      enabled: false

  sql:
    init:   # resources ??? data.sql ?? ??? embeded DB? ?? ?(??? ?)?? ? ???, ?? ? ???, ?? ??? ??
      mode: always

---
# yaml ????? ---? ???? ?? ?? ?? ?? ??? ????

spring:
  config:
    activate:
      on-profile: testdb  # testdb ????? ???? ?? ??? ??
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always


